// Generated by gencpp from file robot/m_Header.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_M_HEADER_H
#define ROBOT_MESSAGE_M_HEADER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot
{
template <class ContainerAllocator>
struct m_Header_
{
  typedef m_Header_<ContainerAllocator> Type;

  m_Header_()
    : header()
    , encL(0)
    , encR(0)  {
    }
  m_Header_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , encL(0)
    , encR(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _encL_type;
  _encL_type encL;

   typedef uint32_t _encR_type;
  _encR_type encR;





  typedef boost::shared_ptr< ::robot::m_Header_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::m_Header_<ContainerAllocator> const> ConstPtr;

}; // struct m_Header_

typedef ::robot::m_Header_<std::allocator<void> > m_Header;

typedef boost::shared_ptr< ::robot::m_Header > m_HeaderPtr;
typedef boost::shared_ptr< ::robot::m_Header const> m_HeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::m_Header_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::m_Header_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot::m_Header_<ContainerAllocator1> & lhs, const ::robot::m_Header_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.encL == rhs.encL &&
    lhs.encR == rhs.encR;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot::m_Header_<ContainerAllocator1> & lhs, const ::robot::m_Header_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot::m_Header_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::m_Header_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::m_Header_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::m_Header_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::m_Header_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::m_Header_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::m_Header_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc65232a7e871f803f44662610342278";
  }

  static const char* value(const ::robot::m_Header_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc65232a7e871f80ULL;
  static const uint64_t static_value2 = 0x3f44662610342278ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::m_Header_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/m_Header";
  }

  static const char* value(const ::robot::m_Header_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::m_Header_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 encL\n"
"uint32 encR\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot::m_Header_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::m_Header_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.encL);
      stream.next(m.encR);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct m_Header_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::m_Header_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::m_Header_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "encL: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encL);
    s << indent << "encR: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encR);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_M_HEADER_H
